# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Blog Michaely Vodové
author: Michaela Vodová
email: michaela.vodova@pirati.cz
description: > # this means to ignore newlines until "baseurl:"
  Zápisník
  Michaely Vodové
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.michaelavodova.cz" # the base hostname & protocol for your site, e.g. http://example.com
keywords: Michaela Vodová
#twitter_username: ondrej_profant
#github_username:  kedrigern
facebook_username: michaela.vodova
#cover_image: /assets/img/design/cover.jpg
#img: /assets/img/ondrej-profant.jpg
#disqus: profant-eu
permalink: /:year/:title:output_ext

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - package.json
  - package-lock.json


sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules

paginate_path: "/stranka/:num/"
paginate: 5
excerpt_separator: <!--more-->
